export const LOGIN = 'auth/LOGIN';

export const LOGOUT = 'auth/LOGOUT';

export const REGISTER_PENDING = 'auth/REGISTER_PENDING';
export const REGISTER_SUCCESS = 'auth/REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'auth/REGISTER_FAILURE';

export const LOGIN_PENDING = 'auth/LOGIN_PENDING';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'auth/LOGIN_FAILURE';

export const PATCH_USER = 'auth/PATCH_USER';


// policies
export const GET_AVAILABLE_POLICIES_PENDING = 'policies/GET_AVAILABLE_POLICIES_PENDING';
export const GET_AVAILABLE_POLICIES_SUCCESS = 'policies/GET_AVAILABLE_POLICIES_SUCCESS';
export const GET_AVAILABLE_POLICIES_FAILURE = 'policies/GET_AVAILABLE_POLICIES_FAILURE';

// need to rethink this
export const GET_USER_POLICIES_PENDING = 'policies/GET_USER_POLICIES_PENDING';
export const GET_USER_POLICIES_SUCCESS = 'policies/GET_USER_POLICIES_SUCCESS';
export const GET_USER_POLICIES_FAILURE = 'policies/GET_USER_POLICIES_FAILURE';

// pods
export const GET_SINGLE_POD_PENDING = 'pods/GET_SINGLE_POD_PENDING';
export const GET_SINGLE_POD_SUCCESS = 'pods/GET_SINGLE_POD_SUCCESS';
export const GET_SINGLE_POD_FAILURE = 'pods/GET_SINGLE_POD_FAILURE';

export const CREATE_POD_PENDING = 'pods/CREATE_POD_PENDING';
export const CREATE_POD_SUCCESS = 'pods/CREATE_POD_SUCCESS';
export const CREATE_POD_FAILURE = 'pods/CREATE_POD_FAILURE';

