# Generated by Django 4.0.4 on 2022-05-18 04:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0002_claim_created_at_claim_updated_at_claimapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='premium_amount',
            field=models.IntegerField(default=500, help_text='in cents', validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='in cents', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums_paid', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='policies.policy')),
            ],
        ),
    ]
