# Generated by Django 4.0.4 on 2022-05-18 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_premium_amount_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='coverage_duration',
            field=models.IntegerField(default=12, help_text='Duration of policy, in months', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(36)]),
        ),
        migrations.AddField(
            model_name='policy',
            name='coverage_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='premium_payment_frequency',
            field=models.IntegerField(choices=[(0, 'Yearly'), (1, 'Monthly'), (2, 'Quarterly')], default=0, help_text='How often premiums are due,'),
        ),
        migrations.AddField(
            model_name='premium',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PolicyCloseout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('premiums_returned_amount', models.IntegerField(help_text='in cents', validators=[django.core.validators.MinValueValidator(1)])),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='close_out', to='policies.policy')),
            ],
        ),
    ]
