# Generated by Django 4.0.4 on 2022-05-25 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_policy_pool_address_alter_policy_governance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date premiums are due'),
            preserve_default=False,
        ),
    ]
