# Generated by Django 4.0.4 on 2022-05-25 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_premium_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='claim_payout_limit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='max_pool_size',
            field=models.IntegerField(blank=True, help_text='\n        Only related to Capped Pool policies.\n        The maximum size of the collected premiums. Once hit, the policy no longer collects premiums until a claim gets paid out of the pool\n        None means no limit.\n        ', null=True, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
