# Generated by Django 4.0.4 on 2022-05-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_rename_policy_type_policy_premium_pool_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='premium_payment_frequency',
            field=models.IntegerField(choices=[(1, 'Monthly'), (3, 'Quarterly'), (12, 'Yearly')], default=1, help_text='How often premiums are due, in months. 1 means monthly, 3 means quarterly, etc.'),
        ),
    ]
