# Generated by Django 4.0.4 on 2022-05-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_alter_policy_premium_payment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimapproval',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimapproval',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimapproval',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
