# Generated by Django 4.0.4 on 2022-05-30 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_claimapproval_approved_claimapproval_approved_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='amount',
            field=models.IntegerField(default=1, help_text='in cents', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='paid_on',
            field=models.DateField(blank=True, help_text='Null means not paid yet', null=True),
        ),
        migrations.AddField(
            model_name='claimapproval',
            name='viewed_on',
            field=models.DateTimeField(blank=True, help_text='When the approver viewed the approval. Helpful to nudge those who let stuff pile up. Wuick turnarounds on claims is a better user experience', null=True),
        ),
    ]
