# Generated by Django 4.0.4 on 2022-05-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_claim_amount_claim_paid_on_claimapproval_viewed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claiment',
            new_name='claimant',
        ),
        migrations.AlterField(
            model_name='claimapproval',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
