# Generated by Django 4.0.4 on 2022-05-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0013_claim_description_claim_title_claimevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='pool_balance',
            field=models.IntegerField(default=0, help_text='In cents'),
        ),
    ]
