# Generated by Django 4.0.4 on 2022-05-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0014_policy_pool_balance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('policy', 'claimant', 'title', 'description', 'amount'), name='user-claim-unique'),
        ),
    ]
