# Generated by Django 4.0.4 on 2022-05-31 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0015_claim_user-claim-unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='lifetime_payout_limit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
