# Generated by Django 4.0.4 on 2022-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0016_policy_lifetime_payout_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_claim_invalid',
            field=models.BooleanField(default=False, help_text="If true, claim can't be paid out, regardless of approval status"),
        ),
    ]
