# Generated by Django 4.1a1 on 2022-06-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pods", "0006_alter_pod_max_pod_size"),
        ("policies", "0017_claim_is_claim_invalid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="pod",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy",
                to="pods.pod",
            ),
        ),
    ]
