# Generated by Django 4.1a1 on 2022-07-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0018_alter_policy_pod"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
