# Generated by Django 4.1a1 on 2022-08-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0021_alter_risk_value_at_risk"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioEquipmentRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(blank=True, max_length=128, null=True)),
                ("model", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "Brand New"),
                            ("near_perfect", "Near Perfect"),
                            ("great", "Great"),
                            ("good", "Good"),
                            ("ok", "ok"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "market_value",
                    models.IntegerField(blank=True, help_text="in cents", null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhoneRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(blank=True, max_length=128, null=True)),
                ("model", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "Brand New"),
                            ("near_perfect", "Near Perfect"),
                            ("great", "Great"),
                            ("good", "Good"),
                            ("ok", "ok"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "market_value",
                    models.IntegerField(blank=True, help_text="in cents", null=True),
                ),
                ("has_screen_protector", models.BooleanField(default=False)),
                ("has_case", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
