# Generated by Django 4.0.6 on 2022-08-02 13:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0022_audioequipmentrisk_phonerisk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='underlying_insured_type',
        ),
        migrations.AddField(
            model_name='policy',
            name='underlying_insured_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cell_phone', 'Phone'), ('audio_equipment', 'Audio Equipment')], default='cell_phone', max_length=26),
            preserve_default=False,
        ),
    ]
