# Generated by Django 4.0.6 on 2022-08-06 21:47

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0023_remove_risk_underlying_insured_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='underlying_insured_type',
        ),
        migrations.AddField(
            model_name='policy',
            name='available_underlying_insured_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cell_phone', 'Phone'), ('audio_equipment', 'Audio Equipment')], max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='underlying_insured_type',
            field=models.CharField(blank=True, choices=[('cell_phone', 'Phone'), ('audio_equipment', 'Audio Equipment')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
