# Generated by Django 4.0.6 on 2022-08-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0024_remove_policy_underlying_insured_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='available_underlying_insured_type',
            new_name='available_underlying_insured_types',
        ),
    ]
