# Generated by Django 4.1 on 2022-08-09 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("policies", "0026_alter_policy_available_underlying_insured_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risk",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "policies"), ("model", "phonerisk")),
                    models.Q(
                        ("app_label", "policies"), ("model", "audioequipmentrisk")
                    ),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
