# Generated by Django 4.1 on 2022-08-16 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0027_alter_risk_content_type_alter_risk_object_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyRiskSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conservative_factor",
                    models.IntegerField(
                        default=1,
                        help_text="how much do you want to pad the risk score by. The higher it is the more premiums everyone pays",
                    ),
                ),
                (
                    "policy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_settings",
                        to="policies.policy",
                    ),
                ),
            ],
        ),
    ]
