# Generated by Django 4.1 on 2022-08-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0028_policyrisksettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="risk",
            name="value_at_risk",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The expected dollar amount loss for a given item computed at the beginning of the policy, in cents",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images")),
                ("default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="policies.imagealbum",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="audioequipmentrisk",
            name="album",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_equipment",
                to="policies.imagealbum",
            ),
        ),
        migrations.AddField(
            model_name="phonerisk",
            name="album",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cell_phone",
                to="policies.imagealbum",
            ),
        ),
    ]
