# Generated by Django 4.1 on 2022-08-26 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("policies", "0030_alter_propertyimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
