# Generated by Django 4.1 on 2022-08-26 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0031_propertyimage_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioequipmentrisk",
            name="album",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audio_equipment",
                to="policies.imagealbum",
            ),
        ),
        migrations.AlterField(
            model_name="phonerisk",
            name="album",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cell_phone",
                to="policies.imagealbum",
            ),
        ),
    ]
