# Generated by Django 4.1 on 2022-08-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0032_alter_audioequipmentrisk_album_alter_phonerisk_album"),
    ]

    operations = [
        migrations.CreateModel(
            name="Peril",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("icon_name", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="policy",
            name="claim_approval_threshold_percentage",
            field=models.IntegerField(
                default=50,
                help_text="Percentage of members that must vote yes to approve a claim",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="perils",
            field=models.ManyToManyField(
                blank=True, related_name="policies", to="policies.peril"
            ),
        ),
    ]
