# Generated by Django 4.1 on 2022-09-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0033_peril_policy_claim_approval_threshold_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="premium",
            name="paid_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
