# Generated by Django 4.1 on 2022-09-28 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0034_premium_paid_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="policyrisksettings",
            name="annual_discount_rate",
            field=models.IntegerField(
                default=0,
                help_text="Annual interest rate that escrow balance could be invested at, in basis points. 100 = 1%",
            ),
        ),
        migrations.AddField(
            model_name="policyrisksettings",
            name="audio_equipment_peril_rate",
            field=models.IntegerField(
                default=20,
                help_text="audio_equipment base peril rate",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="policyrisksettings",
            name="cell_phone_peril_rate",
            field=models.IntegerField(
                default=15,
                help_text="cell_phone base peril rate",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
