# Generated by Django 4.1 on 2022-09-28 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0035_policyrisksettings_annual_discount_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyrisksettings",
            name="audio_equipment_peril_rate",
            field=models.IntegerField(
                default=15,
                help_text="audio_equipment base peril rate",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="policyrisksettings",
            name="cell_phone_peril_rate",
            field=models.IntegerField(
                default=10,
                help_text="cell_phone base peril rate",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="policyrisksettings",
            name="conservative_factor",
            field=models.IntegerField(
                default=0,
                help_text="how much do you want to pad the risk score by. The higher it is the more premiums everyone pays",
            ),
        ),
        migrations.AlterField(
            model_name="risk",
            name="risk_score",
            field=models.IntegerField(
                blank=True,
                help_text="In basis points. The percent chance that a complete loss will happen in the period",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
