# Generated by Django 4.1 on 2022-10-04 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "policies",
            "0036_alter_policyrisksettings_audio_equipment_peril_rate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="policyrisksettings",
            name="cell_phone_case_discount",
            field=models.IntegerField(
                default=100, help_text="cell_phone case discount, absolute basis points"
            ),
        ),
        migrations.AddField(
            model_name="policyrisksettings",
            name="cell_phone_screen_protector_discount",
            field=models.IntegerField(
                default=100, help_text="cell_phone case discount, absolute basis points"
            ),
        ),
        migrations.AlterField(
            model_name="policyrisksettings",
            name="cell_phone_peril_rate",
            field=models.IntegerField(
                default=10,
                help_text="cell_phone base peril rate, percent per year",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
