# Generated by Django 4.1 on 2022-10-16 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("policies", "0037_policyrisksettings_cell_phone_case_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="escrow_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
