# Generated by Django 4.1 on 2022-10-16 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("policies", "0038_policy_escrow_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="premium",
            name="marked_paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="premiums_marked_paid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
