# Generated by Django 4.1.1 on 2022-11-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0040_policyrisksettings_last_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="claim_approval_vote_due_number_of_days",
            field=models.IntegerField(
                default=7,
                help_text="Number of days after a claim is submitted that the vote is due without penalty",
            ),
        ),
    ]
