# Generated by Django 4.1.1 on 2022-11-09 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("policies", "0043_claimcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimcomment",
            name="commenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
