# Generated by Django 4.1.3 on 2022-11-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0045_claim_location_lat_claim_location_long_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="location_description",
            field=models.TextField(
                blank=True,
                help_text="If the location is not precise, you can describe it here",
                null=True,
            ),
        ),
    ]
