# Generated by Django 4.1.3 on 2022-11-20 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("policies", "0046_claim_location_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimevidence",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_evidence",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="claimevidence",
            name="policy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_evidence",
                to="policies.policy",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="claimevidence",
            name="claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="policies.claim",
            ),
        ),
    ]
