# Generated by Django 4.1.3 on 2022-11-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0047_claimevidence_owner_claimevidence_policy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimevidence",
            name="url",
        ),
        migrations.AddField(
            model_name="claimevidence",
            name="image",
            field=models.ImageField(
                default=1, max_length=264, upload_to="claim_evidence_images"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="claimevidence",
            name="photo_order",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Order of photos in the claim",
                null=True,
            ),
        ),
    ]
