# Generated by Django 4.1.3 on 2022-11-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0049_claimview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimapproval",
            name="approved",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
