# Generated by Django 4.1.3 on 2022-11-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0050_alter_claimapproval_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="approved_on",
            field=models.DateTimeField(
                blank=True,
                help_text="The first instant where enough votes were cast to approve the claim",
                null=True,
            ),
        ),
    ]
