# Generated by Django 4.1.3 on 2023-01-10 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("elections", "0001_initial"),
        ("policies", "0054_renewal_date_extension_renewal_initiator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renewal",
            name="date_extension",
            field=models.DateTimeField(
                help_text="The date the policy will be extended to"
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="election",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renewals",
                to="elections.election",
            ),
        ),
        migrations.AlterField(
            model_name="renewal",
            name="initiator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_renewals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
