# Generated by Django 4.1.3 on 2023-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "policies",
            "0055_alter_renewal_date_extension_alter_renewal_election_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="renewal",
            name="date_extension",
        ),
        migrations.AddField(
            model_name="renewal",
            name="months_extension",
            field=models.IntegerField(
                default=1, help_text="The number of months to extend the policy by"
            ),
            preserve_default=False,
        ),
    ]
