# Generated by Django 4.1.3 on 2023-01-19 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0056_remove_renewal_date_extension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="renewal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="renewal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
