# Generated by Django 4.2.2 on 2023-07-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0058_alter_renewal_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyrisksettings",
            name="conservative_factor",
            field=models.IntegerField(
                default=0,
                help_text="how much do you want to pad the risk score by. The higher it is the more premiums everyone pays. Int from 0-100 which will be converted to %",
            ),
        ),
    ]
