# Generated by Django 5.0b1 on 2023-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0059_alter_policyrisksettings_conservative_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk",
            name="is_premium_amount_overridden",
            field=models.BooleanField(
                default=False,
                help_text="If true, the premium amount was overridden by the escrow agent",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="premium_amount_overridden_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the escrow agent overrode the premium",
                null=True,
            ),
        ),
    ]
