# Generated by Django 4.2.2 on 2023-07-31 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gatherer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylifeexpectancyguess",
            name="is_guessor_audited_authority",
            field=models.BooleanField(
                default=False,
                help_text="Means the user is the producer/a large consumer of the property type, and is therefore their guess is more likely to be accurate",
            ),
        ),
        migrations.AddField(
            model_name="propertylifeexpectancyguess",
            name="property_make",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="propertylifeexpectancyguess",
            name="property_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="propertylifeexpectancyguess",
            name="yearly_loss_rate_bsp",
            field=models.IntegerField(
                blank=True,
                help_text="The basis point representation of the property value that is lost each year, mostly calculated from the losses but could be maually set by an audited authority",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PropertyLifeLossGuess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loss_months_into_ownership", models.IntegerField()),
                ("loss_percent", models.IntegerField()),
                (
                    "loss_reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged"),
                            ("lost", "lost"),
                            ("stolen", "Earthquake"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "guess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="losses",
                        to="gatherer.propertylifeexpectancyguess",
                    ),
                ),
            ],
        ),
    ]
