# Generated by Django 4.2.2 on 2023-08-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gatherer",
            "0002_propertylifeexpectancyguess_is_guessor_audited_authority_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylifeexpectancyguess",
            name="purchase_date",
            field=models.DateTimeField(
                blank=True, help_text="The date the property was purchased", null=True
            ),
        ),
        migrations.AddField(
            model_name="propertylifeexpectancyguess",
            name="purchase_price",
            field=models.IntegerField(
                blank=True,
                help_text="The original purchase price of the property, in the cents",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="propertylifelossguess",
            name="loss_cost",
            field=models.IntegerField(
                default=100, help_text="The cost of the loss in cents"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="propertylifelossguess",
            name="loss_reason",
            field=models.CharField(
                choices=[
                    ("damaged", "Damaged"),
                    ("lost", "Lost"),
                    ("stolen", "Stolen"),
                ],
                max_length=255,
            ),
        ),
    ]
