# Generated by Django 4.2.2 on 2023-08-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gatherer", "0003_propertylifeexpectancyguess_purchase_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylifelossguess",
            name="loss_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertylifelossguess",
            name="loss_months_into_ownership",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propertylifelossguess",
            name="loss_percent",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
