# Generated by Django 4.2.2 on 2023-08-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gatherer",
            "0005_rename_loss_cost_propertylifelossguess_loss_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="policylineproperty",
            name="search_tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
