# Generated by Django 4.2.2 on 2023-08-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gatherer", "0006_policylineproperty_search_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policylineproperty",
            name="search_tags",
            field=models.TextField(blank=True, help_text="comma separated", null=True),
        ),
        migrations.AlterField(
            model_name="propertylifeexpectancyguess",
            name="property_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
