# Generated by Django 4.2.2 on 2023-08-20 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("gatherer", "0007_alter_policylineproperty_search_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylifelossguess",
            name="loss_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
