# Generated by Django 4.2.2 on 2023-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gatherer", "0008_alter_propertylifelossguess_loss_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylifelossguess",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("damaged", "Damaged"),
                    ("lost", "Lost"),
                    ("stolen", "Stolen"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertylifelossguess",
            name="loss_reason",
            field=models.CharField(max_length=1024),
        ),
    ]
